version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"  

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8800:8800"  
