FROM node:16 as build

WORKDIR /app

# Copie os arquivos de lock do yarn
COPY ./frontnend/yarn.lock ./
COPY ./frontnend/package.json ./
RUN yarn install

COPY ./frontnend ./
RUN yarn build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
